import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReport = (insights, predictions, strategies) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  doc.setFillColor(79, 70, 229); // Indigo
  doc.rect(0, 0, pageWidth, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('🚀 AI Business Growth Consultant', pageWidth / 2, 13, { align: 'center' });

  // --- Subheader ---
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
  doc.text(`Generated on: ${dateStr} at ${timeStr}`, pageWidth - 10, 28, { align: 'right' });

  // --- Section: Executive Summary ---
  let yPos = 35;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Executive Summary', 14, yPos);
  yPos += 6;

  // KPI Cards (simulated as a nice table)
  const summaryData = [
    ['Total Customers', insights?.total_customers ?? 'N/A'],
    ['Avg Churn Risk', insights?.avg_churn_probability !== null ? `${(insights.avg_churn_probability * 100).toFixed(1)}%` : 'N/A'],
    ['High Risk Customers', insights?.high_risk_count ?? 'N/A'],
    ['Avg Predicted Revenue', insights?.avg_predicted_revenue !== null ? `$${insights.avg_predicted_revenue.toFixed(2)}` : 'N/A'],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    tableWidth: 'auto',
  });

  yPos = doc.lastAutoTable.finalY + 8;

  // --- Section: Prediction Results ---
  if (predictions && predictions.predictions && predictions.predictions.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text('Prediction Results', 14, yPos);
    yPos += 6;

    const predBody = predictions.predictions.map((pred, idx) => {
      const prob = predictions.probabilities ? predictions.probabilities[idx] : null;
      const risk = prob !== null ? (prob > 0.6 ? 'High' : prob > 0.3 ? 'Moderate' : 'Low') : 'N/A';
      return [
        `Customer ${idx + 1}`,
        prob !== null ? (prob * 100).toFixed(1) + '%' : 'N/A',
        risk,
        pred === 1 ? 'Will Churn' : 'Will Stay'
      ];
    });

    autoTable(doc, {
      startY: yPos,
      head: [['Customer', 'Probability', 'Risk Level', 'Prediction']],
      body: predBody,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
      tableWidth: 'auto',
    });

    yPos = doc.lastAutoTable.finalY + 8;
  }

  // --- Section: Actionable Strategies ---
  if (strategies && strategies.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text('Actionable Strategies', 14, yPos);
    yPos += 6;

    const strategyBody = strategies.map((s) => [
      `Customer ${s.customer}`,
      s.risk_level,
      s.predicted_revenue !== null && s.predicted_revenue !== undefined ? `$${s.predicted_revenue.toFixed(2)}` : 'N/A',
      s.advice.substring(0, 40) + '...',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Customer', 'Risk', 'Revenue', 'Advice (Preview)']],
      body: strategyBody,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
      tableWidth: 'auto',
    });

    yPos = doc.lastAutoTable.finalY + 8;
  }

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by AI Business Growth Consultant', 14, pageHeight - 5);
  doc.text(`Page 1`, pageWidth - 14, pageHeight - 5, { align: 'right' });

  // Save the PDF
  doc.save('business_growth_report.pdf');
};